name: CrazyK9s - Pedigree
favicon: null
layout_spectrum: 0.5444725342094898
typography_spectrum: 0.9470534925349057
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4973860702011734
  lightness: 0.9406117973849177
  saturation: 0.11037125089205801
  rhythmicContrast: 0.17257036035880446
purpose: []
